import img0 from './img/0.jpg';
import img1 from './img/1.jpg';
import img2 from './img/2.jpg';
import img3 from './img/3.jpg';
import img4 from './img/4.jpg';
import img5 from './img/5.jpg';
import img6 from './img/6.jpg';
import img7 from './img/7.jpg';
import img9 from './img/9.jpg';
import img10 from './img/10.jpg';
let courses = [{
    id: '1',
    title: 'neutal networks and for deep learning',
    price: '200',
    level: 'beginner',
    topics: 'design',
    courselanguages: 'english',
    duration: 'short',
    mode: 'offline',
    feature: '1',
    collaboration: 'yes',
    img: img0,
    teacher: 'David  Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '300',
    watched: '1203'
},
{
    id: '2',
    title: 'neutal networks and for deep learning',
    price: '150',
    level: 'middle',
    topics: 'programming',
    courselanguages: 'english',
    duration: 'short',
    mode: 'offline',
    feature: '1',
    collaboration: 'yes',
    img: img1,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '100',
    watched: '1203'
},
{
    id: '3',
    title: 'neutal networks and for deep learning',
    price: '300',
    level: 'advanced',
    topics: 'web development',
    courselanguages: 'english',
    duration: 'long',
    mode: 'offline',
    feature: '1',
    collaboration: 'yes',
    img: img2,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '203',
    watched: '1203'
},
{
    id: '4',
    title: 'neutal networks and for deep learning',
    price: '120',
    level: 'beginner',
    topics: 'mobile app',
    courselanguages: 'english',
    duration: 'short',
    mode: 'offline',
    feature: '1',
    collaboration: 'yes',
    img: img3,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '40',
    watched: '1203'
},{
    id: '5',
    title: 'neutal networks and for deep learning',
    price: '200',
    level: 'beginner',
    topics: 'process',
    courselanguages: 'franch',
    duration: 'short',
    mode: 'online',
    feature: '1',
    collaboration: 'no',
    img: img5,
    teacher: 'David  Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '342',
    watched: '1203'
},
{
    id: '6',
    title: 'neutal networks and for deep learning',
    price: '150',
    level: 'middle',
    topics: 'programming',
    courselanguages: 'english',
    duration: 'short',
    mode: 'online',
    feature: '1',
    collaboration: 'yes',
    img: img6,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '100',
    watched: '1203'
},
{
    id: '7',
    title: 'neutal networks and for deep learning',
    price: '142',
    level: 'middle',
    topics: 'mobile app',
    courselanguages: 'franch',
    duration: 'long',
    mode: 'offline',
    feature: '1',
    collaboration: 'yes',
    img: img7,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '203',
    watched: '1203'
},
{
    id: '8',
    title: 'neutal networks and for deep learning',
    price: '120',
    level: 'beginner',
    topics: 'mobile app',
    courselanguages: 'italian',
    duration: 'short',
    mode: 'online',
    feature: '2',
    collaboration: 'no',
    img: img0,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '155',
    watched: '1203'
},{
    id: '9',
    title: 'neutal networks and for deep learning',
    price: '345',
    level: 'middle',
    topics: 'design',
    courselanguages: 'italian',
    duration: 'short',
    mode: 'offline',
    feature: '2',
    collaboration: 'yes',
    img: img4,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '455',
    watched: '3234'
},
{
    id: '10',
    title: 'neutal networks and for deep learning',
    price: '120',
    level: 'advanced',
    topics: 'mobile app',
    courselanguages: 'english',
    duration: 'long',
    mode: 'online',
    feature: '2',
    collaboration: 'no',
    img: img0,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '434',
    watched: '1203'
},{
    id: '11',
    title: 'neutal networks and for deep learning',
    price: '345',
    level: 'beginner',
    topics: 'process',
    courselanguages: 'italian',
    duration: 'short',
    mode: 'offline',
    feature: '2',
    collaboration: 'yes',
    img: img4,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '455',
    watched: '3234'
},
{
    id: '12',
    title: 'neutal networks and for deep learning',
    price: '400',
    level: 'advanced',
    topics: 'programming',
    courselanguages: 'english',
    duration: 'short',
    mode: 'online',
    feature: '2',
    collaboration: 'no',
    img: img3,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '600',
    watched: '1203'
},{
    id: '13',
    title: 'neutal networks and for deep learning',
    price: '345',
    level: 'middle',
    topics: 'design',
    courselanguages: 'italian',
    duration: 'short',
    mode: 'offline',
    feature: '2',
    collaboration: 'yes',
    img: img6,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '455',
    watched: '3234'
},
{
    id: '14',
    title: 'neutal networks and for deep learning',
    price: '300',
    level: 'middle',
    topics: 'web development',
    courselanguages: 'english',
    duration: 'short',
    mode: 'online',
    feature: '2',
    collaboration: 'yea',
    img: img9,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '600',
    watched: '1203'
},{
    id: '15',
    title: 'neutal networks and for deep learning',
    price: '500',
    level: 'beginner',
    topics: 'mobile app',
    courselanguages: 'italian',
    duration: 'short',
    mode: 'offline',
    feature: '2',
    collaboration: 'yes',
    img: img7,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '455',
    watched: '3234'
},
{
    id: '16',
    title: 'neutal networks and for deep learning',
    price: '99',
    level: 'advanced',
    topics: 'design',
    courselanguages: 'english',
    duration: 'short',
    mode: 'online',
    feature: '2',
    collaboration: 'no',
    img: img0,
    teacher: 'David Beckham',
    teacherFoto: 'https://www.atomix.com.au/media/2015/06/atomix_user31.png',
    rating: '600',
    watched: '1203'
}]

export default courses;